#!/usr/bin/env python3
"""grove launcher: works from a symlink anywhere on PATH."""
import os
import sys

if sys.version_info < (3, 11):
    sys.exit("grove needs Python 3.11 or newer (found %d.%d)" % sys.version_info[:2])

sys.path.insert(0, os.path.dirname(os.path.realpath(__file__)))

from grove_core.cli import main  # noqa: E402

sys.exit(main())
